###Product Metadata
GET http://localhost:4004/odata/v4/aircraft/$metadata

###Get Products
GET http://localhost:4004/odata/v4/product/Products?$expand=to_Purchase,to_Sales,status,to_Size
Accept-Language: 'en'

###Search Aircraft by range
GET http://localhost:4004/odata/v4/aircraft/searchAeroplaneByRange(range=5000)

### Process Generic Entity
POST http://localhost:4004/odata/v4/aviation/processGenericInput
Content-Type: application/json

{
        "userPrompt": "Create draft entry for Boeing 787, range around 7000 KM with capacity of 300 passengers",
        "entityName": "Aircrafts",
        "chatHistory": ""
}


### Delete Product
DELETE http://localhost:4004/odata/v4/product/Products(ID='00000000-0000-0000-0000-000000000001')


###Request changes for supplier product
PATCH http://localhost:4004/odata/v4/product/Products/00000000-0000-0000-0000-000000000003
Content-Type: application/json

{
        "status": "ReleasedForSupplier",
        "topicComponent_ID":"64817147-c2a0-508e-a35a-831969066bg8",
        "module_ID":"44d2212c-d27e-411d-8f11-f9ddb3105d3e",

        "sizeSystem_ID": "Test",
        "availableFrom": "2023-10-01",
        "availableUntil": "2023-12-31",
        "endOfLifeCycle": "2024-01-01",

        "currency_ID": "EUR",

        "gridBox_ID": "Test",
        "omnichannel": "TestValue",

        "addHangTag_ID": "TestEinkäufter"

}

###Create Product with existing KT
POST http://localhost:4004/odata/v4/product/UploadProducts
Content-Type: application/json

{
        "sizeSystem": "Test",
        "availableFrom": "2023-10-01",
        "availableUntil": "2023-12-31",
        "endOfLifeCycle": "2024-01-01",
        "portion1": "20",
        "material2": "00000000-0000-0000-0000-000000000001",
        "portion2": "20",
        "material3": "00000000-0000-0000-0000-000000000001",
        "portion3": "20",
        "material4": "00000000-0000-0000-0000-000000000001",
        "portion4": "20",
        "material5": "00000000-0000-0000-0000-000000000001",
        "portion5": "20",
        "presentationType": "Presentation Type 2",
        "material1": "Test Material 1",
        "supplierProductNumber": "1",
        "supplierColor": "Yellow",
        "size": "M",
        "GTIN": "TEST",

        "currency": "EUR",

        "additionalProperties": {
                "supplier_ID":"98664237-ce10-433c-867d-3d46a3cde3c5",
                "consumerTopic_ID": "f4444355-50a0-42ac-bb88-6823da932952",
                "brand_ID": "33a2212c-a27b-411a-8d88-c9ddb3105a0b"
        }
}

###Get Products
GET http://localhost:4004/odata/v4/product/ProductsToWritingAppointments?$expand=deliveryDate

###Get Products
PUT http://localhost:4004/odata/v4/product/ProductsToWritingAppointments(product_ID='00000000-0000-0000-0000-000000000001',writingAppointment_ID='4f2b6c1d-967d-4295-bbdf-b0a3e1ea1f77')
Content-Type: application/json

{
        "deliveryDates": [{"date": "2026-05-05"},{"date": "2025-05-05"}]
}

### Get Image URL
GET http://localhost:4004/odata/v4/product/Products/00000000-0000-0000-0000-000000000001/getImageUrl()

###Mark for Deletion - Article
POST http://localhost:4004/odata/v4/product/Articles/d4f5b036-736a-4330-91d0-dada497b9609/markForDeletion
Content-Type: application/json