GET http://localhost:4004/odata/v4/consumer-topic-brand/SupplierConsumerTopicBrands(supplierID_supplierID=1,consumerTopic_consumerTopicID=1,brandNumber_brandNumberID=1)

###
GET http://localhost:4004/odata/v4/consumer-topic-brand/SupplierConsumerTopicBrands

###
GET http://localhost:4004/odata/v4/consumer-topic-brand/$metadata

###
GET http://localhost:4004/odata/v4/consumer-topic-brand/Suppliers(ID='1')

###
GET http://localhost:4004/odata/v4/consumer-topic-brand/SupplierConsumerTopicBrands

####
GET http://localhost:4004/odata/v4/writing-appointment/WritingAppointments

###
GET http://localhost:4004/odata/v4/access-control-data/Groups

###
GET http://localhost:4004/odata/v4/access-control-data/Users('anonymous')/assignedGroups(user_ID='anonymous',group_ID=1)

###
GET http://localhost:4004/odata/v4/access-control-data/UserGroups

###
GET http://localhost:4004/odata/v4/access-control-data/ConsumerTopics

###
GET http://localhost:4004/odata/v4/access-control-data/VHConsumerTopics
GET http://localhost:4004/odata/v4/consumer-topic-brand/ConsumerTopicBrandService/$metadata

###
GET http://localhost:4004/odata/v4/consumer-topic-brand/ConsumerTopicBrandService/Suppliers(supplierID='1')

###
GET http://localhost:4004/odata/v4/consumer-topic-brand/ConsumerTopicBrandService/$metadata