###Product Metadata
GET http://localhost:4004/odata/v2/planning/$metadata

###Get Products
GET http://localhost:4004/odata/v2/planning/Planning?$expand=products
Accept-Language: 'en'

###Get Products temp
GET http://localhost:4004/odata/v2/planning/WritingAppointments


###Create Product with KT warning
POST http://localhost:4004/odata/v2/planning/Planning?$expand=products
Content-Type: application/json

{
        "supplier_ID":"98664237-ce10-433c-867d-3d46a3cde3c5",
        "consumerTopic_ID": "f4444355-50a0-42ac-bb88-6823da932952",
        "brand_ID": "66f2212c-f280-411f-8123-b9ddb3105f5g",
        "writingAppointment_ID": "3f86e888-12f3-4cc1-b3fa-7a238c31c4cc",
        "status_ID": "ToCheck",
        "purchaseVolume": 12332341
}

###
GET http://localhost:4004/odata/v2/planning/WRF_CHARVAL
Content-Type: application/json

{
        "ID":"InProgress",
        "name":"Test Status"
}


###Create Product with existing KT
GET http://localhost:4004/odata/v4/product/Products
Content-Type: application/json

{
        "supplier_ID":"98664237-ce10-433c-867d-3d46a3cde3c5",

        "sizeSystem_ID": "Test",
        "availableFrom": "2023-10-01",
        "availableUntil": "2023-12-31",
        "endOfLifeCycle": "2024-01-01",

        "gridBox_ID": "Test",
        "omnichannel": "TestValue",

        "addHangTag_ID": "Test",

        "consumerTopic_ID": "f4444355-50a0-42ac-bb88-6823da932952",
        "brand_ID": "33a2212c-a27b-411a-8d88-c9ddb3105a0b"

}  

### Delete Product
DELETE http://localhost:4004/odata/v4/product/Products(ID='00000000-0000-0000-0000-000000000001')


###Request changes for supplier product
PATCH http://localhost:4004/odata/v4/product/Products/00000000-0000-0000-0000-000000000003
Content-Type: application/json

{
        "status": "ReleasedForSupplier",
        "topicComponent_ID":"64817147-c2a0-508e-a35a-831969066bg8",
        "module_ID":"44d2212c-d27e-411d-8f11-f9ddb3105d3e",

        "sizeSystem_ID": "Test",
        "availableFrom": "2023-10-01",
        "availableUntil": "2023-12-31",
        "endOfLifeCycle": "2024-01-01",

        "currency_ID": "EUR",

        "gridBox_ID": "Test",
        "omnichannel": "TestValue",

        "addHangTag_ID": "TestEinkäufter"

}

###Get whether product is existing
GET http://localhost:4004/odata/v4/product/checkForExistingProduct(supplierProductNumber='TestName',GTIN='TestGTIN')

###Create Product with existing KT
POST http://localhost:4004/odata/v4/product/UploadProducts
Content-Type: application/json

{
        "sizeSystem": "Test",
        "availableFrom": "2023-10-01",
        "availableUntil": "2023-12-31",
        "endOfLifeCycle": "2024-01-01",
        "portion1": "20",
        "material2": "00000000-0000-0000-0000-000000000001",
        "portion2": "20",
        "material3": "00000000-0000-0000-0000-000000000001",
        "portion3": "20",
        "material4": "00000000-0000-0000-0000-000000000001",
        "portion4": "20",
        "material5": "00000000-0000-0000-0000-000000000001",
        "portion5": "20",
        "presentationType": "Presentation Type 2",
        "material1": "Test Material 1",
        "supplierProductNumber": "1",
        "supplierColor": "Yellow",
        "size": "M",
        "GTIN": "TEST",

        "currency": "EUR",

        "additionalProperties": {
                "supplier_ID":"98664237-ce10-433c-867d-3d46a3cde3c5",
                "consumerTopic_ID": "f4444355-50a0-42ac-bb88-6823da932952",
                "brand_ID": "33a2212c-a27b-411a-8d88-c9ddb3105a0b"
        }
}

###Get Products
GET http://localhost:4004/odata/v4/product/ProductsToWritingAppointments?$expand=deliveryDate

###Get Products
PUT http://localhost:4004/odata/v4/product/ProductsToWritingAppointments(product_ID='00000000-0000-0000-0000-000000000001',writingAppointment_ID='4f2b6c1d-967d-4295-bbdf-b0a3e1ea1f77')
Content-Type: application/json

{
        "deliveryDates": [{"date": "2026-05-05"},{"date": "2025-05-05"}]
}

### Get Image URL
GET http://localhost:4004/odata/v4/product/Products/00000000-0000-0000-0000-000000000001/getImageUrl()

###Create Product with KT warning
GET http://localhost:4004/odata/v4/product/ProductStatus?$expand=texts

###Get budget of HG
GET http://localhost:4004/odata/v4/planning/getBudgetHG(planning_ID='550e8400-e29b-41d4-a716-446655440001')