###Product Metadata
GET http://localhost:4004/odata/v4/product/$metadata

### Read Supplier Products
GET http://localhost:4004/odata/v4/product/SupplierProducts

###Create Supplier Product
POST http://localhost:4004/odata/v4/product/SupplierProducts
Content-Type: application/json

{
        "topicComponent_ID":"64817147-c2a0-508e-a35a-831969066bg8",
        "module_ID":"44d2212c-d27e-411d-8f11-f9ddb3105d3e",

        "sizeSystem_ID": "Test",
        "availableFrom": "2023-10-01",
        "availableUntil": "2023-12-31",
        "endOfLifeCycle": "2024-01-01",

        "currency_ID": "EUR",

        "gridBox_ID": "Test",
        "omnichannel": "TestValue",

        "addHangTag_ID": "Test"

}

### No Product Deletion for Suppliers
DELETE http://localhost:4004/odata/v4/product/SupplierProducts(ID='00000000-0000-0000-0000-000000000003')

###Update Supplier Product
PATCH http://localhost:4004/odata/v4/product/SupplierProducts/00000000-0000-0000-0000-000000000003
Content-Type: application/json

{
        "topicComponent_ID":"64817147-c2a0-508e-a35a-831969066bg8",
        "module_ID":"44d2212c-d27e-411d-8f11-f9ddb3105d3e",

        "sizeSystem_ID": "Test",
        "availableFrom": "2023-10-01",
        "availableUntil": "2023-12-31",
        "endOfLifeCycle": "2024-01-01",

        "currency_ID": "EUR",

        "gridBox_ID": "Test",
        "omnichannel": "TestValue",

        "addHangTag_ID": "Test"

}

###UPDATE SUPPLIER PRODUCT
PATCH http://localhost:4004/odata/v4/product/Products/00000000-0000-0000-0000-000000000003
Content-Type: application/json

{
        "status": "ReleasedForSupplier",
        "topicComponent_ID":"64817147-c2a0-508e-a35a-831969066bg8",
        "module_ID":"44d2212c-d27e-411d-8f11-f9ddb3105d3e",

        "sizeSystem_ID": "Test",
        "availableFrom": "2023-10-01",
        "availableUntil": "2023-12-31",
        "endOfLifeCycle": "2024-01-01",

        "currency_ID": "EUR",

        "gridBox_ID": "Test",
        "omnichannel": "TestValue",

        "addHangTag_ID": "TestEinkäufter"

}